#!/bin/bash
#SBATCH -J part1_SUBJ_WALKNUM
#SBATCH -e error_logs/part1_SUBJ_WALKNUM.%j.err
#SBATCH -o output_logs/part1_SUBJ_WALKNUM.%j.out
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p normal
#SBATCH -t 24:00:00
#SBATCH -A IBN21023
#SBATCH --mail-user=karl.muller@utexas.edu
#SBATCH --mail-type=all

$WORK/Meshroom*/meshroom_photogrammetry --input $SCRATCH/MonocularProject/SUBJ/subclip_frames/WALKNUM/ --output $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM --save $SCRATCH/MonocularProject/id_probe_SUBJ_WALKNUM.mg

var=$(grep '"intrinsicId":.*' $SCRATCH/MonocularProject/id_probe_SUBJ_WALKNUM.mg | head -1)
num=$(echo ${var} | cut -c 16- | cut -d ',' -f 1)

rm $SCRATCH/MonocularProject/id_probe_SUBJ_WALKNUM.mg

cp override_config.json overrides/SUBJ_WALKNUM_config.json
sed -i "s/p_match_this/"${num}"/g" overrides/SUBJ_WALKNUM_config.json

mkdir $SCRATCH/MonocularProject/SUBJ/meshroom_output/
mkdir $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/

$WORK/Meshroom*/meshroom_photogrammetry --input $SCRATCH/MonocularProject/SUBJ/subclip_frames/WALKNUM/ --output $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/ --override overrides/SUBJ_WALKNUM_config.json --save $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/this_graph.mg

$WORK/Meshroom*/meshroom_compute $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/this_graph.mg --toNode PrepareDenseScene_1 --cache $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/
