#!/bin/bash
#SBATCH -J part3_SUBJ_WALKNUM
#SBATCH -e error_logs/part1_SUBJ_WALKNUM.%j.err
#SBATCH -o output_logs/part1_SUBJ_WALKNUM.%j.out
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p normal
#SBATCH -t 24:00:00
#SBATCH -A IBN21023
#SBATCH --mail-user=karl.muller@utexas.edu
#SBATCH --mail-type=all

$WORK/Meshroom*/meshroom_compute $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/this_graph.mg --node DepthMapFilter_1 --forceCompute --cache $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/

$WORK/Meshroom*/meshroom_compute $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/this_graph.mg --node Meshing_1 --forceCompute --cache $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/

$WORK/Meshroom*/meshroom_compute $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/this_graph.mg --node MeshFiltering_1 --forceCompute --cache $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/

$WORK/Meshroom*/meshroom_compute $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/this_graph.mg --node Texturing_1 --forceCompute --cache $SCRATCH/MonocularProject/SUBJ/meshroom_output/WALKNUM/
